# Generated by Django 5.0.3 on 2024-04-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_admin',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='message_doner',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
