# Generated by Django 5.0.3 on 2024-04-22 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0008_donation_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='otp',
        ),
    ]
