# Generated by Django 5.0.3 on 2024-05-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0010_alter_category_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='visited',
            field=models.BooleanField(default=False),
        ),
    ]
