# Generated by Django 5.0.3 on 2024-04-09 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appadmin', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=255, null=True)),
                ('pet_breed', models.CharField(max_length=255, null=True)),
                ('pet_image', models.ImageField(null=True, upload_to='image/')),
                ('pet_age', models.IntegerField(null=True)),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appadmin.category')),
            ],
        ),
    ]
