# Generated by Django 5.0.3 on 2024-04-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdonor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
