# Generated by Django 5.0.3 on 2024-05-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdonor', '0003_pet_donor'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='visited',
            field=models.BooleanField(default=False),
        ),
    ]
