# Generated by Django 5.0.3 on 2024-05-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdonor', '0004_pet_visited'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
