# Generated by Django 5.0.3 on 2024-05-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdonor', '0005_pet_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='approved',
            field=models.BooleanField(),
        ),
    ]
