# Generated by Django 5.0.3 on 2024-04-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='adopter_contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='pet_age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='pet_breed',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
