# Generated by Django 5.0.3 on 2024-04-24 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0002_cart_adopter_contact_cart_pet_age_cart_pet_breed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='adopter_contact',
        ),
    ]
