# Generated by Django 5.0.3 on 2024-04-24 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdonor', '0003_pet_donor'),
        ('appuser', '0003_remove_cart_adopter_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='pet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appdonor.pet'),
        ),
    ]
