# Generated by Django 5.0.3 on 2024-04-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0004_cart_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='adoptor_contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='adoptor_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
