# Generated by Django 5.0.3 on 2024-04-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0006_remove_cart_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='pet_id',
            field=models.IntegerField(null=True),
        ),
    ]
