# Generated by Django 5.0.3 on 2024-04-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0008_adoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='donor_id',
            field=models.IntegerField(null=True),
        ),
    ]
