# Generated by Django 5.0.3 on 2024-05-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0010_cart_visited'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='visited2',
            field=models.BooleanField(default=False),
        ),
    ]
