# Generated by Django 5.0.3 on 2024-05-13 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0011_cart_visited2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='donor_contact',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
