# Generated by Django 5.0.3 on 2024-05-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0012_alter_cart_donor_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='adoptor_contact',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
